package com.xiangshan.selfienote.pojo;

public class commodity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.accountId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private String accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.account
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodityId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private String commodityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.name
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.originalPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private Double originalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.sellPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private Double sellprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.inventory
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private Integer inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.sellNumLastMonth
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    private Integer sellnumlastmonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.accountId
     *
     * @return the value of commodity.accountId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.accountId
     *
     * @param accountid the value for commodity.accountId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.account
     *
     * @return the value of commodity.account
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.account
     *
     * @param account the value for commodity.account
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodityId
     *
     * @return the value of commodity.commodityId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public String getCommodityid() {
        return commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodityId
     *
     * @param commodityid the value for commodity.commodityId
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setCommodityid(String commodityid) {
        this.commodityid = commodityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.originalPrice
     *
     * @return the value of commodity.originalPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public Double getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.originalPrice
     *
     * @param originalprice the value for commodity.originalPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setOriginalprice(Double originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sellPrice
     *
     * @return the value of commodity.sellPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public Double getSellprice() {
        return sellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sellPrice
     *
     * @param sellprice the value for commodity.sellPrice
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setSellprice(Double sellprice) {
        this.sellprice = sellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.inventory
     *
     * @return the value of commodity.inventory
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public Integer getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.inventory
     *
     * @param inventory the value for commodity.inventory
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sellNumLastMonth
     *
     * @return the value of commodity.sellNumLastMonth
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public Integer getSellnumlastmonth() {
        return sellnumlastmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sellNumLastMonth
     *
     * @param sellnumlastmonth the value for commodity.sellNumLastMonth
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    public void setSellnumlastmonth(Integer sellnumlastmonth) {
        this.sellnumlastmonth = sellnumlastmonth;
    }
}