package com.xiangshan.selfienote.pojo;

import java.util.Date;

public class store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.accountId
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private String accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.account
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.password
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.lastProfitDate
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Date lastprofitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.deadline
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.todayProfit
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Double todayprofit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.querySuccessTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Integer querysuccesstimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.queryFailTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private Integer queryfailtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.lastLogAccount
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private String lastlogaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.lastLogPassword
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    private String lastlogpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.accountId
     *
     * @return the value of store.accountId
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.accountId
     *
     * @param accountid the value for store.accountId
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.account
     *
     * @return the value of store.account
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.account
     *
     * @param account the value for store.account
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.password
     *
     * @return the value of store.password
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.password
     *
     * @param password the value for store.password
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.lastProfitDate
     *
     * @return the value of store.lastProfitDate
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Date getLastprofitdate() {
        return lastprofitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.lastProfitDate
     *
     * @param lastprofitdate the value for store.lastProfitDate
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setLastprofitdate(Date lastprofitdate) {
        this.lastprofitdate = lastprofitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.deadline
     *
     * @return the value of store.deadline
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.deadline
     *
     * @param deadline the value for store.deadline
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.todayProfit
     *
     * @return the value of store.todayProfit
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Double getTodayprofit() {
        return todayprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.todayProfit
     *
     * @param todayprofit the value for store.todayProfit
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setTodayprofit(Double todayprofit) {
        this.todayprofit = todayprofit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.querySuccessTimes
     *
     * @return the value of store.querySuccessTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Integer getQuerysuccesstimes() {
        return querysuccesstimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.querySuccessTimes
     *
     * @param querysuccesstimes the value for store.querySuccessTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setQuerysuccesstimes(Integer querysuccesstimes) {
        this.querysuccesstimes = querysuccesstimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.queryFailTimes
     *
     * @return the value of store.queryFailTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public Integer getQueryfailtimes() {
        return queryfailtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.queryFailTimes
     *
     * @param queryfailtimes the value for store.queryFailTimes
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setQueryfailtimes(Integer queryfailtimes) {
        this.queryfailtimes = queryfailtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.lastLogAccount
     *
     * @return the value of store.lastLogAccount
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public String getLastlogaccount() {
        return lastlogaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.lastLogAccount
     *
     * @param lastlogaccount the value for store.lastLogAccount
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setLastlogaccount(String lastlogaccount) {
        this.lastlogaccount = lastlogaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.lastLogPassword
     *
     * @return the value of store.lastLogPassword
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public String getLastlogpassword() {
        return lastlogpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.lastLogPassword
     *
     * @param lastlogpassword the value for store.lastLogPassword
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    public void setLastlogpassword(String lastlogpassword) {
        this.lastlogpassword = lastlogpassword;
    }
}