package com.xiangshan.selfienote.mappers;

import com.xiangshan.selfienote.pojo.commodity;
import com.xiangshan.selfienote.pojo.commodityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface commodityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int countByExample(commodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int deleteByExample(commodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int insert(commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int insertSelective(commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    List<commodity> selectByExample(commodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    commodity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") commodity record, @Param("example") commodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int updateByExample(@Param("record") commodity record, @Param("example") commodityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int updateByPrimaryKeySelective(commodity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbggenerated Mon Mar 25 21:16:37 CST 2019
     */
    int updateByPrimaryKey(commodity record);
}