package com.xiangshan.selfienote.mappers;

import com.xiangshan.selfienote.pojo.store;
import com.xiangshan.selfienote.pojo.storeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface storeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int countByExample(storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int deleteByExample(storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int insert(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int insertSelective(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    List<store> selectByExample(storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") store record, @Param("example") storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int updateByExample(@Param("record") store record, @Param("example") storeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int updateByPrimaryKeySelective(store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbggenerated Mon Mar 25 23:15:04 CST 2019
     */
    int updateByPrimaryKey(store record);
}